services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: togrul
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  full-stack-professional:
    container_name: full-stack-professional
    image: togrulmamishov/full-stack-professional
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
networks:
  db:
    driver: bridge

volumes:
  db:
