services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: togrul
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  customer-api:
    container_name: customer-api
    image: togrulmamishov/spring-boot-fullstack
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  customer-api-react:
    container_name: customer-api-react
    image: togrulmamishov/customer-api-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8080
    ports:
      - "3000:5173"
    depends_on:
      - customer-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
